/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    Donut: typeof import('./components/donut.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Image: typeof import('./components/Image.vue')['default']
    ItemCard: typeof import('./components/ItemCard.vue')['default']
    ItemWindow: typeof import('./components/ItemWindow.vue')['default']
    Navbar: typeof import('./components/navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
